-- ==========================================================
-- UDV - HM_ESTADISTICAS_PARTIDOS (limpio)
-- Proyecto: Liga 1 Perú
-- ==========================================================

CREATE OR REPLACE TABLE ${catalog_name}.tb_udv.hm_estadisticas_partidos (
  id_partido           STRING   COMMENT 'Identificador único del partido (hash de temporada + URL).',
  id_equipo_local      INT      COMMENT 'ID técnico del equipo local.',
  id_equipo_visitante  INT      COMMENT 'ID técnico del equipo visitante.',
  temporada            INT      COMMENT 'Temporada (año) del partido.',
  estado               STRING   COMMENT 'Estado del registro de estadísticas (si aplica).',
  marcador             STRING   COMMENT 'Marcador en texto, por ejemplo 2 - 1.',
  goles_local          INT      COMMENT 'Goles del equipo local (derivado de marcador).',
  goles_visitante      INT      COMMENT 'Goles del equipo visitante (derivado de marcador).',
  url                  STRING   COMMENT 'URL de detalle del partido en FotMob.',
  fecha_stats          DATE     COMMENT 'Fecha del partido según estadísticas (dd-MM-yyyy).',
  regates_realizados_local       INT     COMMENT 'Regates realizados por el equipo local.',
  regates_realizados_local_pct   DOUBLE  COMMENT 'Proporción de regates realizados por el local (0–1) extraída de la cadena N (P %).',
  tiros_postes_visitante         INT     COMMENT 'Tiros a los postes del equipo visitante.',
  duelo_terrestre_visitante      INT     COMMENT 'Duelos terrestres ganados por el visitante.',
  duelo_terrestre_visitante_pct  DOUBLE  COMMENT 'Proporción de duelos terrestres ganados por el visitante (0–1).',
  duelo_terrestre_local          INT     COMMENT 'Duelos terrestres ganados por el local.',
  duelo_terrestre_local_pct      DOUBLE  COMMENT 'Proporción de duelos terrestres ganados por el local (0–1).',
  saques_esquina_local           INT     COMMENT 'Saques de esquina ejecutados por el local.',
  tarjetas_amarillas_visitante   INT     COMMENT 'Tarjetas amarillas mostradas al visitante.',
  mitad_rival_visitante          INT     COMMENT 'Acciones del visitante en mitad rival (unidad FotMob).',
  pases_visitante                INT     COMMENT 'Pases totales del equipo visitante.',
  intercepciones_local           INT     COMMENT 'Intercepciones del equipo local.',
  despejes_visitante             INT     COMMENT 'Despejes realizados por el visitante.',
  tarjetas_rojas_visitante       INT     COMMENT 'Tarjetas rojas mostradas al visitante.',
  tarjetas_rojas_local           INT     COMMENT 'Tarjetas rojas mostradas al local.',
  tiros_postes_local             INT     COMMENT 'Tiros a los postes del equipo local.',
  tiros_fuera_area_local         INT     COMMENT 'Tiros del local realizados fuera del área.',
  gran_probabilidad_local        INT     COMMENT 'Grandes ocasiones generadas por el local.',
  disparos_fuera_local           INT     COMMENT 'Disparos del local que salieron fuera del arco.',
  tiros_largos_precisos_visitante      INT     COMMENT 'Pases largos precisos del visitante.',
  tiros_largos_precisos_visitante_pct  DOUBLE  COMMENT 'Proporción de pases largos precisos del visitante (0–1).',
  interceptaciones_visitante           INT     COMMENT 'Interceptaciones del visitante (métrica alternativa al campo con “c”/“t”).',
  aereo_ganado_visitante               INT     COMMENT 'Duelos aéreos ganados por el visitante.',
  aereo_ganado_visitante_pct           DOUBLE  COMMENT 'Proporción de duelos aéreos ganados por el visitante (0–1).',
  tarjetas_amarillas_local             INT     COMMENT 'Tarjetas amarillas mostradas al local.',
  aereo_ganado_local                   INT     COMMENT 'Duelos aéreos ganados por el local.',
  aereo_ganado_local_pct               DOUBLE  COMMENT 'Proporción de duelos aéreos ganados por el local (0–1).',
  tiros_libres_precisos_local          INT     COMMENT 'Tiros libres precisos ejecutados por el local.',
  tiros_libres_precisos_local_pct      DOUBLE  COMMENT 'Proporción de tiros libres precisos del local (0–1).',
  lanzamientos_visitante               INT     COMMENT 'Lanzamientos (saques de banda u otros) del visitante.',
  disparos_puerta_local                INT     COMMENT 'Disparos a puerta realizados por el local.',
  paradas_portero_visitante            INT     COMMENT 'Paradas realizadas por el portero visitante.',
  tiros_bloqueados_visitante           INT     COMMENT 'Tiros del visitante bloqueados por la defensa rival.',
  toques_area_rival_visitante          INT     COMMENT 'Toques del visitante en el área rival.',
  tiros_area_visitante                 INT     COMMENT 'Tiros del visitante realizados dentro del área.',
  tiros_totales_visitante              INT     COMMENT 'Tiros totales del visitante.',
  duelos_ganados_visitante             INT     COMMENT 'Duelos ganados por el visitante.',
  gran_probabilidad_visitante          INT     COMMENT 'Grandes ocasiones generadas por el visitante.',
  mitad_propia_visitante               INT     COMMENT 'Acciones del visitante en mitad propia.',
  disparos_puerta_visitante            INT     COMMENT 'Disparos a puerta realizados por el visitante.',
  pases_local                          INT     COMMENT 'Pases totales del equipo local.',
  tiros_totales_local                  INT     COMMENT 'Tiros totales del local.',
  tiros_libres_precisos_visitante      INT     COMMENT 'Tiros libres precisos ejecutados por el visitante.',
  tiros_libres_precisos_visitante_pct  DOUBLE  COMMENT 'Proporción de tiros libres precisos del visitante (0–1).',
  tiros_area_local                     INT     COMMENT 'Tiros del local realizados dentro del área.',
  faltas_visitante                     INT     COMMENT 'Faltas cometidas por el visitante.',
  interceptaciones_local               INT     COMMENT 'Interceptaciones del local (segunda métrica de interceptación en origen).',
  mitad_propia_local                   INT     COMMENT 'Acciones del local en mitad propia.',
  regates_realizados_visitante         INT     COMMENT 'Regates realizados por el equipo visitante.',
  regates_realizados_visitante_pct     DOUBLE  COMMENT 'Proporción de regates realizados por el visitante (0–1).',
  duelos_ganados_local                 INT     COMMENT 'Duelos ganados por el local.',
  saques_esquina_visitante             INT     COMMENT 'Saques de esquina ejecutados por el visitante.',
  entradas_local                       INT     COMMENT 'Entradas (tackles) realizadas por el local.',
  entradas_visitante                   INT     COMMENT 'Entradas (tackles) realizadas por el visitante.',
  disparos_fuera_visitante             INT     COMMENT 'Disparos del visitante que salieron fuera del arco.',
  pases_precisos_visitante             INT     COMMENT 'Pases precisos realizados por el visitante.',
  pases_precisos_visitante_pct         DOUBLE  COMMENT 'Proporción de pases precisos del visitante (0–1).',
  pases_precisos_local                 INT     COMMENT 'Pases precisos realizados por el local.',
  pases_precisos_local_pct             DOUBLE  COMMENT 'Proporción de pases precisos del local (0–1).',
  tiros_bloqueados_local               INT     COMMENT 'Tiros del local bloqueados por la defensa rival.',
  mitad_rival_local                    INT     COMMENT 'Acciones del local en mitad rival.',
  paradas_portero_local                INT     COMMENT 'Paradas realizadas por el portero local.',
  fueras_juego_local                   INT     COMMENT 'Fueras de juego cometidos por el local.',
  tiros_largos_precisos_local          INT     COMMENT 'Pases largos precisos del local.',
  tiros_largos_precisos_local_pct      DOUBLE  COMMENT 'Proporción de pases largos precisos del local (0–1).',
  faltas_local                         INT     COMMENT 'Faltas cometidas por el local.',
  grandes_oportunidades_perdidas_visitante INT COMMENT 'Grandes ocasiones claras falladas por el visitante.',
  grandes_oportunidades_perdidas_local     INT COMMENT 'Grandes ocasiones claras falladas por el local.',
  fueras_juego_visitante               INT     COMMENT 'Fueras de juego cometidos por el visitante.',
  toques_area_rival_local              INT     COMMENT 'Toques del local en el área rival.',
  despejes_local                       INT     COMMENT 'Despejes realizados por el local.',
  lanzamientos_local                   INT     COMMENT 'Lanzamientos (saques de banda u otros) del local.',
  tiros_fuera_area_visitante           INT     COMMENT 'Tiros del visitante realizados fuera del área.',
  fecha_carga  TIMESTAMP COMMENT 'Fecha y hora de la carga en UDV.',
  fuente       STRING    COMMENT 'Fuente de las estadísticas, por ejemplo FotMob.',
  periodo      INT       COMMENT 'Periodo técnico de carga (YYYY), normalmente igual a temporada.'
)
USING delta
PARTITIONED BY (periodo)
LOCATION 'abfss://${container_name}@${storage_account}.dfs.core.windows.net/udv/Proyecto/liga1/tb_udv/hm_estadisticas_partidos/data'
COMMENT 'Histórico de estadísticas partido a partido de Liga 1 Perú, con métricas de local/visitante y columnas *_pct solo para métricas que vienen en formato N (P %).';
