-- ==========================================================
-- DDV - FT_PARTIDOS_DETALLE
-- Proyecto: Liga 1 Perú
-- ==========================================================

CREATE OR REPLACE TABLE ${catalog_name}.tb_ddv.ft_partidos_detalle (
  id_partido                           STRING        NOT NULL COMMENT 'Identificador único del partido (hash de temporada + URL)',
  id_equipo_local                      INT                    COMMENT 'ID del equipo local',
  nombre_equipo_local                  STRING                 COMMENT 'Nombre oficial del equipo local',
  alias_equipo_local                   STRING                 COMMENT 'Alias del equipo local',
  id_equipo_visitante                  INT                    COMMENT 'ID del equipo visitante',
  nombre_equipo_visitante              STRING                 COMMENT 'Nombre oficial del equipo visitante',
  alias_equipo_visitante               STRING                 COMMENT 'Alias del equipo visitante',
  temporada                            INT                    COMMENT 'Temporada (año) del partido',
  fecha_partido                        DATE                   COMMENT 'Fecha del partido',
  marcador                             STRING                 COMMENT 'Marcador final (ej. 2 - 1)',
  goles_local                          INT                    COMMENT 'Goles del equipo local',
  goles_visitante                      INT                    COMMENT 'Goles del equipo visitante',
  estado                               STRING                 COMMENT 'Estado del registro de estadísticas',
  fecha_stats                          DATE                   COMMENT 'Fecha del partido según fuente de estadísticas',
  regates_realizados_local             INT                    COMMENT 'Regates realizados por el equipo local',
  regates_realizados_local_pct         DOUBLE                 COMMENT 'Proporción de regates del local (0–1)',
  tiros_postes_visitante               INT                    COMMENT 'Tiros a los postes del visitante',
  duelo_terrestre_visitante            INT                    COMMENT 'Duelos terrestres ganados por el visitante',
  duelo_terrestre_visitante_pct        DOUBLE                 COMMENT 'Proporción de duelos terrestres del visitante (0–1)',
  duelo_terrestre_local                INT                    COMMENT 'Duelos terrestres ganados por el local',
  duelo_terrestre_local_pct            DOUBLE                 COMMENT 'Proporción de duelos terrestres del local (0–1)',
  saques_esquina_local                 INT                    COMMENT 'Saques de esquina del local',
  tarjetas_amarillas_visitante         INT                    COMMENT 'Tarjetas amarillas del visitante',
  mitad_rival_visitante                INT                    COMMENT 'Acciones del visitante en mitad rival',
  pases_visitante                      INT                    COMMENT 'Pases totales del visitante',
  intercepciones_local                 INT                    COMMENT 'Intercepciones del local',
  despejes_visitante                   INT                    COMMENT 'Despejes del visitante',
  tarjetas_rojas_visitante             INT                    COMMENT 'Tarjetas rojas del visitante',
  tarjetas_rojas_local                 INT                    COMMENT 'Tarjetas rojas del local',
  tiros_postes_local                   INT                    COMMENT 'Tiros a los postes del local',
  tiros_fuera_area_local               INT                    COMMENT 'Tiros del local fuera del área',
  gran_probabilidad_local              INT                    COMMENT 'Grandes ocasiones del local',
  disparos_fuera_local                 INT                    COMMENT 'Disparos del local fuera del arco',
  tiros_largos_precisos_visitante      INT                    COMMENT 'Pases largos precisos del visitante',
  tiros_largos_precisos_visitante_pct  DOUBLE                 COMMENT 'Proporción de pases largos precisos del visitante (0–1)',
  interceptaciones_visitante           INT                    COMMENT 'Interceptaciones del visitante',
  aereo_ganado_visitante               INT                    COMMENT 'Duelos aéreos ganados por el visitante',
  aereo_ganado_visitante_pct           DOUBLE                 COMMENT 'Proporción de duelos aéreos del visitante (0–1)',
  tarjetas_amarillas_local             INT                    COMMENT 'Tarjetas amarillas del local',
  aereo_ganado_local                   INT                    COMMENT 'Duelos aéreos ganados por el local',
  aereo_ganado_local_pct               DOUBLE                 COMMENT 'Proporción de duelos aéreos del local (0–1)',
  tiros_libres_precisos_local          INT                    COMMENT 'Tiros libres precisos del local',
  tiros_libres_precisos_local_pct      DOUBLE                 COMMENT 'Proporción de tiros libres precisos del local (0–1)',
  lanzamientos_visitante               INT                    COMMENT 'Lanzamientos del visitante',
  disparos_puerta_local                INT                    COMMENT 'Disparos a puerta del local',
  paradas_portero_visitante            INT                    COMMENT 'Paradas del portero visitante',
  tiros_bloqueados_visitante           INT                    COMMENT 'Tiros del visitante bloqueados',
  toques_area_rival_visitante          INT                    COMMENT 'Toques del visitante en área rival',
  tiros_area_visitante                 INT                    COMMENT 'Tiros del visitante dentro del área',
  tiros_totales_visitante              INT                    COMMENT 'Tiros totales del visitante',
  duelos_ganados_visitante             INT                    COMMENT 'Duelos ganados por el visitante',
  gran_probabilidad_visitante          INT                    COMMENT 'Grandes ocasiones del visitante',
  mitad_propia_visitante               INT                    COMMENT 'Acciones del visitante en mitad propia',
  disparos_puerta_visitante            INT                    COMMENT 'Disparos a puerta del visitante',
  pases_local                          INT                    COMMENT 'Pases totales del local',
  tiros_totales_local                  INT                    COMMENT 'Tiros totales del local',
  tiros_libres_precisos_visitante      INT                    COMMENT 'Tiros libres precisos del visitante',
  tiros_libres_precisos_visitante_pct  DOUBLE                 COMMENT 'Proporción de tiros libres precisos del visitante (0–1)',
  tiros_area_local                     INT                    COMMENT 'Tiros del local dentro del área',
  faltas_visitante                     INT                    COMMENT 'Faltas cometidas por el visitante',
  interceptaciones_local               INT                    COMMENT 'Interceptaciones del local (segunda métrica)',
  mitad_propia_local                   INT                    COMMENT 'Acciones del local en mitad propia',
  regates_realizados_visitante         INT                    COMMENT 'Regates realizados por el visitante',
  regates_realizados_visitante_pct     DOUBLE                 COMMENT 'Proporción de regates del visitante (0–1)',
  duelos_ganados_local                 INT                    COMMENT 'Duelos ganados por el local',
  saques_esquina_visitante             INT                    COMMENT 'Saques de esquina del visitante',
  entradas_local                       INT                    COMMENT 'Entradas (tackles) del local',
  entradas_visitante                   INT                    COMMENT 'Entradas (tackles) del visitante',
  disparos_fuera_visitante             INT                    COMMENT 'Disparos del visitante fuera del arco',
  pases_precisos_visitante             INT                    COMMENT 'Pases precisos del visitante',
  pases_precisos_visitante_pct         DOUBLE                 COMMENT 'Proporción de pases precisos del visitante (0–1)',
  pases_precisos_local                 INT                    COMMENT 'Pases precisos del local',
  pases_precisos_local_pct             DOUBLE                 COMMENT 'Proporción de pases precisos del local (0–1)',
  tiros_bloqueados_local               INT                    COMMENT 'Tiros del local bloqueados',
  mitad_rival_local                    INT                    COMMENT 'Acciones del local en mitad rival',
  paradas_portero_local                INT                    COMMENT 'Paradas del portero local',
  fueras_juego_local                   INT                    COMMENT 'Fueras de juego del local',
  tiros_largos_precisos_local          INT                    COMMENT 'Pases largos precisos del local',
  tiros_largos_precisos_local_pct      DOUBLE                 COMMENT 'Proporción de pases largos precisos del local (0–1)',
  faltas_local                         INT                    COMMENT 'Faltas cometidas por el local',
  grandes_oportunidades_perdidas_visitante INT                COMMENT 'Grandes ocasiones falladas por el visitante',
  grandes_oportunidades_perdidas_local     INT                COMMENT 'Grandes ocasiones falladas por el local',
  fueras_juego_visitante               INT                    COMMENT 'Fueras de juego del visitante',
  toques_area_rival_local              INT                    COMMENT 'Toques del local en área rival',
  despejes_local                       INT                    COMMENT 'Despejes del local',
  lanzamientos_local                   INT                    COMMENT 'Lanzamientos del local',
  tiros_fuera_area_visitante           INT                    COMMENT 'Tiros del visitante fuera del área',
  posesion_local                       INT                    COMMENT 'Porcentaje de posesión del local (valor entero)',
  posesion_local_pct                   DOUBLE                 COMMENT 'Posesión del local como proporción (0–1)',
  posesion_visitante                   INT                    COMMENT 'Porcentaje de posesión del visitante (valor entero)',
  posesion_visitante_pct               DOUBLE                 COMMENT 'Posesión del visitante como proporción (0–1)',
  centros_precisos_local               INT                    COMMENT 'Centros precisos del local (Accurate crosses)',
  centros_precisos_visitante           INT                    COMMENT 'Centros precisos del visitante (Accurate crosses)',
  bloqueos_local                       INT                    COMMENT 'Bloqueos del local (Blocks)',
  bloqueos_visitante                   INT                    COMMENT 'Bloqueos del visitante (Blocks)',
  url                                  STRING                 COMMENT 'URL del partido en la fuente',
  fuente_partido                       STRING                 COMMENT 'Fuente del registro de partido',
  fecha_carga                          TIMESTAMP     NOT NULL COMMENT 'Fecha y hora de la carga en DDV',
  periodo                              INT           NOT NULL COMMENT 'Periodo técnico de carga en formato YYYY'
)
USING delta
PARTITIONED BY (periodo)
LOCATION 'abfss://${container_name}@${storage_account}.dfs.core.windows.net/${ruta_base}/ddv/ft_partidos_detalle/data'
COMMENT 'Fact de partidos con estadísticas detalladas por partido (local/visitante) enriquecido con nombres de equipo de la Liga 1 Perú.';
